import { Component, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { TranslocoModule } from '@jsverse/transloco';
import { PhysicsTilesComponent } from './physics-tiles/physics-tiles.component';
import { TILE_IMAGES } from './physics-tiles/tiles.manifest';

@Component({
  selector: 'app-hero',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TranslocoModule, PhysicsTilesComponent],
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.scss'],
})
export class HeroComponent {
  @Output() requestClicked = new EventEmitter<void>();
  @Output() contactClicked = new EventEmitter<void>();

  /** Photo tiles for the animated physics backdrop (auto-generated by gen-tiles.mjs). */
  readonly tileImages = TILE_IMAGES;
}
