FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build user-app --configuration=production --skip-nx-cache

FROM nginx:alpine
COPY --from=builder /app/dist/apps/user-app/browser /usr/share/nginx/html
COPY nginx.user.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
