FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build admin-app --configuration=production --skip-nx-cache

FROM nginx:alpine
COPY --from=builder /app/dist/apps/admin-app/browser /usr/share/nginx/html
COPY nginx.admin.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
