// Generate hero physics-tile thumbnails + a manifest from collage-src.
//
// Drop any number of photos into ./collage-src, then run:
//   node gen-tiles.mjs
//
// It (re)builds small webp tiles in the user-app assets and writes a manifest
// the hero imports, so the animation always matches whatever photos exist —
// no code edits needed.

import sharp from 'sharp';
import { readdir, writeFile, unlink, mkdir } from 'node:fs/promises';
import { join, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, 'collage-src');
const TILES_DIR = join(__dirname, 'apps/user-app/src/assets/images/tiles');
const MANIFEST = join(
  __dirname,
  'apps/user-app/src/app/features/home/components/hero/physics-tiles/tiles.manifest.ts',
);
const LONG_EDGE = 300; // px — thumbnails stay small for fast texture loading
const IMG_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.tif', '.tiff']);

async function main() {
  await mkdir(TILES_DIR, { recursive: true });

  // clear out any previous tiles so removed photos don't linger
  for (const f of await readdir(TILES_DIR)) {
    if (/^tile-\d+\.webp$/.test(f)) await unlink(join(TILES_DIR, f));
  }

  const photos = (await readdir(SRC))
    .filter((f) => IMG_EXT.has(extname(f).toLowerCase()))
    .sort();

  if (photos.length === 0) {
    console.error(`No photos in ${SRC}.`);
    process.exit(1);
  }

  const names = [];
  await Promise.all(
    photos.map(async (f, i) => {
      const name = `tile-${String(i + 1).padStart(2, '0')}.webp`;
      await sharp(join(SRC, f))
        .rotate() // respect EXIF orientation
        .resize(LONG_EDGE, LONG_EDGE, { fit: 'inside', withoutEnlargement: true })
        .webp({ quality: 80 })
        .toFile(join(TILES_DIR, name));
      names[i] = name;
    }),
  );

  const list = names.map((n) => `  'assets/images/tiles/${n}',`).join('\n');
  const manifest = `// AUTO-GENERATED by gen-tiles.mjs — do not edit by hand.
// Re-run \`node gen-tiles.mjs\` after adding/removing photos in collage-src/.
export const TILE_IMAGES: string[] = [
${list}
];
`;
  await writeFile(MANIFEST, manifest, 'utf8');

  console.log(`✓ ${names.length} tiles → ${TILES_DIR}`);
  console.log(`✓ manifest → ${MANIFEST}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
