// AUTO-GENERATED by gen-tiles.mjs — do not edit by hand.
// Re-run `node gen-tiles.mjs` after adding/removing photos in collage-src/.
export const TILE_IMAGES: string[] = [
  'assets/images/tiles/tile-01.webp',
  'assets/images/tiles/tile-02.webp',
  'assets/images/tiles/tile-03.webp',
  'assets/images/tiles/tile-04.webp',
  'assets/images/tiles/tile-05.webp',
  'assets/images/tiles/tile-06.webp',
  'assets/images/tiles/tile-07.webp',
  'assets/images/tiles/tile-08.webp',
  'assets/images/tiles/tile-09.webp',
  'assets/images/tiles/tile-10.webp',
  'assets/images/tiles/tile-11.webp',
  'assets/images/tiles/tile-12.webp',
  'assets/images/tiles/tile-13.webp',
];
