name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/lilia-paws-front
            git fetch origin
            git reset --hard origin/main
            cd /var/www/lilia-paws-back
            docker compose stop user-app admin-app
            docker compose rm -f user-app admin-app
            docker compose up -d --build user-app admin-app